# Generated by Django 5.2.13 on 2026-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, unique=True, verbose_name='адрес')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('geocoded_at', models.DateTimeField(db_index=True, verbose_name='дата запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'кэш адреса',
                'verbose_name_plural': 'кэш адресов',
            },
        ),
    ]
