# Generated by Django 5.2.13 on 2026-04-19 05:47

from django.db import migrations


def copy_product_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = list(OrderItem.objects.select_related('product'))
    for item in order_items:
        item.price = item.product.price
    OrderItem.objects.bulk_update(order_items, ['price'])

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(copy_product_price, migrations.RunPython.noop),
    ]
