# Generated by Django 5.2.13 on 2026-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В работе'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен')], db_index=True, default='new', max_length=20, verbose_name='статус'),
        ),
    ]
