# Generated by Django 5.2.13 on 2026-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('electronic', 'Электронно')], db_index=True, max_length=20, verbose_name='способ оплаты'),
        ),
    ]
